name: diabetic-retinopathy-detection

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - dask
  - gh
  - python=3.8
  - git
  - kaggle
  - jupyterlab
  - jupyterlab-nvdashboard
  - lightning
  - nbgitpuller
  - pytorch
  - pytorch-cuda=11.8
  - scikit-learn
  - torchvision
  
